name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
            .yarn
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn set version berry
      - run: yarn install --frozen-lockfile
      - run: yarn lint --force
  build:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
            .yarn
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn set version berry
      - run: yarn install --frozen-lockfile
      - run: |
          yarn build --force
          yarn package --force
